app:
  message: Message has been sent Successfully..
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: message.exchange
    queue: messageAudit.queue
    routingkey: messageAudit.routingkey
    cache:
      channel:
          checkout-timeout: 10000
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9091
#logging:
 # level:
  #  root: DEBUG
   # org.springframework: DEBUG
#    com.howtodoinjava: DEBUG
 #   org.hibernate: ERROR