app:
  message: Message has been sent Successfully..
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: message.exchange
    queue: messageAudit.queue
    routingkey: messageAudit.routingkey
server:
  port: 8080
datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
h2:
  console:
    enabled: true
    path: /h2-console
#logging:
 # level:
  #  root: DEBUG
   # org.springframework: DEBUG